### ISSUE TITLE
3D Printed Case files not as per videos and pictures?

### ISSUE THREAD

**Issue by comm** [rbaron/spellcaster#1]
I note the f3d file does not show the same design as the pictures and video on the readme - can you please upload the latest version?

Thank you.

**Comment by rbaron** [comment]
Indeed I made a lot of changes after exporting those files. I re-exported them now in the main branch.

If you're really building the whole project, make sure to read the [project status](https://github.com/rbaron/spellcaster?tab=readme-ov-file#project-status). While I'm very excited to see someone building it, keep in mind that this is very experimental and there are many annoying quirks and very rough edges everywhere that can be frustrating. I myself haven't had time to work on it over the past year, so I can only offer limited support.

With that out of the way, please keep me posted on your progress. I'd love to see someone else have some fun with it.

**Comment by comm** [comment]
Superb, thank you. I appreciate the words of caution. Your knowledge to get to this point is well beyond my skill, but I'm sure I'll trouble shoot as best I can before coming your way, but will definitely let you know how it goes.
